name: Deploy FastAPI to Azure Container App

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FASTAPISERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FASTAPISERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FASTAPISERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile
          imageToBuild: fastapiserver.azurecr.io/fastapi-server:${{ github.sha }}
          registryUrl: fastapiserver.azurecr.io
          registryUsername: ${{ secrets.FASTAPISERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FASTAPISERVER_REGISTRY_PASSWORD }}
          containerAppName: fastapi-server
          resourceGroup: fastapi
          containerAppEnvironment: fastapi-server-env
          targetPort: 8000
